packages:
  github.com/snnus/mainservice/internal/services/spservice:
    interfaces:
      SPStorage:
        config:
          dir: internal/services/spservice/mocks
          filename: storage.go
      SPClient:
        config:
          dir: internal/services/spservice/mocks
          filename: client.go
      SPProducer:
        config:
          dir: internal/services/spservice/mocks
          filename: producer.go
