// Code generated by mockery v2.53.5. DO NOT EDIT.

package spservice

import (
	context "context"

	models "github.com/snnus/mainservice/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSPClient is an autogenerated mock type for the SPClient type
type MockSPClient struct {
	mock.Mock
}

type MockSPClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSPClient) EXPECT() *MockSPClient_Expecter {
	return &MockSPClient_Expecter{mock: &_m.Mock}
}

// Dequeue provides a mock function with given fields: ctx, id
func (_m *MockSPClient) Dequeue(ctx context.Context, id string) (*models.Ticket, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 *models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Ticket, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Ticket); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPClient_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type MockSPClient_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSPClient_Expecter) Dequeue(ctx interface{}, id interface{}) *MockSPClient_Dequeue_Call {
	return &MockSPClient_Dequeue_Call{Call: _e.mock.On("Dequeue", ctx, id)}
}

func (_c *MockSPClient_Dequeue_Call) Run(run func(ctx context.Context, id string)) *MockSPClient_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSPClient_Dequeue_Call) Return(_a0 *models.Ticket, _a1 error) *MockSPClient_Dequeue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPClient_Dequeue_Call) RunAndReturn(run func(context.Context, string) (*models.Ticket, error)) *MockSPClient_Dequeue_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function with given fields: ctx, id, shortname
func (_m *MockSPClient) Enqueue(ctx context.Context, id string, shortname string) (*models.Ticket, error) {
	ret := _m.Called(ctx, id, shortname)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 *models.Ticket
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*models.Ticket, error)); ok {
		return rf(ctx, id, shortname)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *models.Ticket); ok {
		r0 = rf(ctx, id, shortname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Ticket)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, shortname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPClient_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockSPClient_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - shortname string
func (_e *MockSPClient_Expecter) Enqueue(ctx interface{}, id interface{}, shortname interface{}) *MockSPClient_Enqueue_Call {
	return &MockSPClient_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, id, shortname)}
}

func (_c *MockSPClient_Enqueue_Call) Run(run func(ctx context.Context, id string, shortname string)) *MockSPClient_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSPClient_Enqueue_Call) Return(_a0 *models.Ticket, _a1 error) *MockSPClient_Enqueue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPClient_Enqueue_Call) RunAndReturn(run func(context.Context, string, string) (*models.Ticket, error)) *MockSPClient_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSPClient creates a new instance of MockSPClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSPClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSPClient {
	mock := &MockSPClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
