// Code generated by mockery v2.53.5. DO NOT EDIT.

package spservice

import (
	context "context"

	models "github.com/snnus/mainservice/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockSPStorage is an autogenerated mock type for the SPStorage type
type MockSPStorage struct {
	mock.Mock
}

type MockSPStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSPStorage) EXPECT() *MockSPStorage_Expecter {
	return &MockSPStorage_Expecter{mock: &_m.Mock}
}

// DeleteServicePoint provides a mock function with given fields: ctx, id
func (_m *MockSPStorage) DeleteServicePoint(ctx context.Context, id string) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServicePoint")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ServicePoint, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ServicePoint); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPStorage_DeleteServicePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServicePoint'
type MockSPStorage_DeleteServicePoint_Call struct {
	*mock.Call
}

// DeleteServicePoint is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSPStorage_Expecter) DeleteServicePoint(ctx interface{}, id interface{}) *MockSPStorage_DeleteServicePoint_Call {
	return &MockSPStorage_DeleteServicePoint_Call{Call: _e.mock.On("DeleteServicePoint", ctx, id)}
}

func (_c *MockSPStorage_DeleteServicePoint_Call) Run(run func(ctx context.Context, id string)) *MockSPStorage_DeleteServicePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSPStorage_DeleteServicePoint_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockSPStorage_DeleteServicePoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPStorage_DeleteServicePoint_Call) RunAndReturn(run func(context.Context, string) (*models.ServicePoint, error)) *MockSPStorage_DeleteServicePoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfficeNumberById provides a mock function with given fields: ctx, is
func (_m *MockSPStorage) GetOfficeNumberById(ctx context.Context, is string) (string, error) {
	ret := _m.Called(ctx, is)

	if len(ret) == 0 {
		panic("no return value specified for GetOfficeNumberById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, is)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, is)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, is)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPStorage_GetOfficeNumberById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfficeNumberById'
type MockSPStorage_GetOfficeNumberById_Call struct {
	*mock.Call
}

// GetOfficeNumberById is a helper method to define mock.On call
//   - ctx context.Context
//   - is string
func (_e *MockSPStorage_Expecter) GetOfficeNumberById(ctx interface{}, is interface{}) *MockSPStorage_GetOfficeNumberById_Call {
	return &MockSPStorage_GetOfficeNumberById_Call{Call: _e.mock.On("GetOfficeNumberById", ctx, is)}
}

func (_c *MockSPStorage_GetOfficeNumberById_Call) Run(run func(ctx context.Context, is string)) *MockSPStorage_GetOfficeNumberById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSPStorage_GetOfficeNumberById_Call) Return(_a0 string, _a1 error) *MockSPStorage_GetOfficeNumberById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPStorage_GetOfficeNumberById_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockSPStorage_GetOfficeNumberById_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicePointByID provides a mock function with given fields: ctx, id
func (_m *MockSPStorage) GetServicePointByID(ctx context.Context, id string) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetServicePointByID")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ServicePoint, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ServicePoint); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPStorage_GetServicePointByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicePointByID'
type MockSPStorage_GetServicePointByID_Call struct {
	*mock.Call
}

// GetServicePointByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockSPStorage_Expecter) GetServicePointByID(ctx interface{}, id interface{}) *MockSPStorage_GetServicePointByID_Call {
	return &MockSPStorage_GetServicePointByID_Call{Call: _e.mock.On("GetServicePointByID", ctx, id)}
}

func (_c *MockSPStorage_GetServicePointByID_Call) Run(run func(ctx context.Context, id string)) *MockSPStorage_GetServicePointByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSPStorage_GetServicePointByID_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockSPStorage_GetServicePointByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPStorage_GetServicePointByID_Call) RunAndReturn(run func(context.Context, string) (*models.ServicePoint, error)) *MockSPStorage_GetServicePointByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetShortNameById provides a mock function with given fields: ctx, is
func (_m *MockSPStorage) GetShortNameById(ctx context.Context, is string) (string, error) {
	ret := _m.Called(ctx, is)

	if len(ret) == 0 {
		panic("no return value specified for GetShortNameById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, is)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, is)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, is)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPStorage_GetShortNameById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShortNameById'
type MockSPStorage_GetShortNameById_Call struct {
	*mock.Call
}

// GetShortNameById is a helper method to define mock.On call
//   - ctx context.Context
//   - is string
func (_e *MockSPStorage_Expecter) GetShortNameById(ctx interface{}, is interface{}) *MockSPStorage_GetShortNameById_Call {
	return &MockSPStorage_GetShortNameById_Call{Call: _e.mock.On("GetShortNameById", ctx, is)}
}

func (_c *MockSPStorage_GetShortNameById_Call) Run(run func(ctx context.Context, is string)) *MockSPStorage_GetShortNameById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSPStorage_GetShortNameById_Call) Return(_a0 string, _a1 error) *MockSPStorage_GetShortNameById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPStorage_GetShortNameById_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockSPStorage_GetShortNameById_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertServicePoint provides a mock function with given fields: ctx, id, sp
func (_m *MockSPStorage) UpsertServicePoint(ctx context.Context, id string, sp models.NewServicePointRequest) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, id, sp)

	if len(ret) == 0 {
		panic("no return value specified for UpsertServicePoint")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.NewServicePointRequest) (*models.ServicePoint, error)); ok {
		return rf(ctx, id, sp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.NewServicePointRequest) *models.ServicePoint); ok {
		r0 = rf(ctx, id, sp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.NewServicePointRequest) error); ok {
		r1 = rf(ctx, id, sp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSPStorage_UpsertServicePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertServicePoint'
type MockSPStorage_UpsertServicePoint_Call struct {
	*mock.Call
}

// UpsertServicePoint is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - sp models.NewServicePointRequest
func (_e *MockSPStorage_Expecter) UpsertServicePoint(ctx interface{}, id interface{}, sp interface{}) *MockSPStorage_UpsertServicePoint_Call {
	return &MockSPStorage_UpsertServicePoint_Call{Call: _e.mock.On("UpsertServicePoint", ctx, id, sp)}
}

func (_c *MockSPStorage_UpsertServicePoint_Call) Run(run func(ctx context.Context, id string, sp models.NewServicePointRequest)) *MockSPStorage_UpsertServicePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.NewServicePointRequest))
	})
	return _c
}

func (_c *MockSPStorage_UpsertServicePoint_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockSPStorage_UpsertServicePoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSPStorage_UpsertServicePoint_Call) RunAndReturn(run func(context.Context, string, models.NewServicePointRequest) (*models.ServicePoint, error)) *MockSPStorage_UpsertServicePoint_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSPStorage creates a new instance of MockSPStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSPStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSPStorage {
	mock := &MockSPStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
