// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMainProducer is an autogenerated mock type for the MainProducer type
type MockMainProducer struct {
	mock.Mock
}

type MockMainProducer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMainProducer) EXPECT() *MockMainProducer_Expecter {
	return &MockMainProducer_Expecter{mock: &_m.Mock}
}

// PublishTicket provides a mock function with given fields: ctx, ticket, officeNumber
func (_m *MockMainProducer) PublishTicket(ctx context.Context, ticket string, officeNumber string) error {
	ret := _m.Called(ctx, ticket, officeNumber)

	if len(ret) == 0 {
		panic("no return value specified for PublishTicket")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, ticket, officeNumber)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMainProducer_PublishTicket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishTicket'
type MockMainProducer_PublishTicket_Call struct {
	*mock.Call
}

// PublishTicket is a helper method to define mock.On call
//   - ctx context.Context
//   - ticket string
//   - officeNumber string
func (_e *MockMainProducer_Expecter) PublishTicket(ctx interface{}, ticket interface{}, officeNumber interface{}) *MockMainProducer_PublishTicket_Call {
	return &MockMainProducer_PublishTicket_Call{Call: _e.mock.On("PublishTicket", ctx, ticket, officeNumber)}
}

func (_c *MockMainProducer_PublishTicket_Call) Run(run func(ctx context.Context, ticket string, officeNumber string)) *MockMainProducer_PublishTicket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockMainProducer_PublishTicket_Call) Return(_a0 error) *MockMainProducer_PublishTicket_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMainProducer_PublishTicket_Call) RunAndReturn(run func(context.Context, string, string) error) *MockMainProducer_PublishTicket_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMainProducer creates a new instance of MockMainProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMainProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMainProducer {
	mock := &MockMainProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
