// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/snnus/mainservice/internal/models"
)

// MockMainStorage is an autogenerated mock type for the MainStorage type
type MockMainStorage struct {
	mock.Mock
}

type MockMainStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMainStorage) EXPECT() *MockMainStorage_Expecter {
	return &MockMainStorage_Expecter{mock: &_m.Mock}
}

// CreateServicePoint provides a mock function with given fields: ctx, sp
func (_m *MockMainStorage) CreateServicePoint(ctx context.Context, sp models.NewServicePointRequest) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, sp)

	if len(ret) == 0 {
		panic("no return value specified for CreateServicePoint")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.NewServicePointRequest) (*models.ServicePoint, error)); ok {
		return rf(ctx, sp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.NewServicePointRequest) *models.ServicePoint); ok {
		r0 = rf(ctx, sp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.NewServicePointRequest) error); ok {
		r1 = rf(ctx, sp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMainStorage_CreateServicePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServicePoint'
type MockMainStorage_CreateServicePoint_Call struct {
	*mock.Call
}

// CreateServicePoint is a helper method to define mock.On call
//   - ctx context.Context
//   - sp models.NewServicePointRequest
func (_e *MockMainStorage_Expecter) CreateServicePoint(ctx interface{}, sp interface{}) *MockMainStorage_CreateServicePoint_Call {
	return &MockMainStorage_CreateServicePoint_Call{Call: _e.mock.On("CreateServicePoint", ctx, sp)}
}

func (_c *MockMainStorage_CreateServicePoint_Call) Run(run func(ctx context.Context, sp models.NewServicePointRequest)) *MockMainStorage_CreateServicePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(models.NewServicePointRequest))
	})
	return _c
}

func (_c *MockMainStorage_CreateServicePoint_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockMainStorage_CreateServicePoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMainStorage_CreateServicePoint_Call) RunAndReturn(run func(context.Context, models.NewServicePointRequest) (*models.ServicePoint, error)) *MockMainStorage_CreateServicePoint_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServicePoint provides a mock function with given fields: ctx, id
func (_m *MockMainStorage) DeleteServicePoint(ctx context.Context, id string) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServicePoint")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ServicePoint, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ServicePoint); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMainStorage_DeleteServicePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServicePoint'
type MockMainStorage_DeleteServicePoint_Call struct {
	*mock.Call
}

// DeleteServicePoint is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMainStorage_Expecter) DeleteServicePoint(ctx interface{}, id interface{}) *MockMainStorage_DeleteServicePoint_Call {
	return &MockMainStorage_DeleteServicePoint_Call{Call: _e.mock.On("DeleteServicePoint", ctx, id)}
}

func (_c *MockMainStorage_DeleteServicePoint_Call) Run(run func(ctx context.Context, id string)) *MockMainStorage_DeleteServicePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMainStorage_DeleteServicePoint_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockMainStorage_DeleteServicePoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMainStorage_DeleteServicePoint_Call) RunAndReturn(run func(context.Context, string) (*models.ServicePoint, error)) *MockMainStorage_DeleteServicePoint_Call {
	_c.Call.Return(run)
	return _c
}

// GetOfficeNumberById provides a mock function with given fields: ctx, is
func (_m *MockMainStorage) GetOfficeNumberById(ctx context.Context, is string) (string, error) {
	ret := _m.Called(ctx, is)

	if len(ret) == 0 {
		panic("no return value specified for GetOfficeNumberById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, is)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, is)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, is)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMainStorage_GetOfficeNumberById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOfficeNumberById'
type MockMainStorage_GetOfficeNumberById_Call struct {
	*mock.Call
}

// GetOfficeNumberById is a helper method to define mock.On call
//   - ctx context.Context
//   - is string
func (_e *MockMainStorage_Expecter) GetOfficeNumberById(ctx interface{}, is interface{}) *MockMainStorage_GetOfficeNumberById_Call {
	return &MockMainStorage_GetOfficeNumberById_Call{Call: _e.mock.On("GetOfficeNumberById", ctx, is)}
}

func (_c *MockMainStorage_GetOfficeNumberById_Call) Run(run func(ctx context.Context, is string)) *MockMainStorage_GetOfficeNumberById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMainStorage_GetOfficeNumberById_Call) Return(_a0 string, _a1 error) *MockMainStorage_GetOfficeNumberById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMainStorage_GetOfficeNumberById_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockMainStorage_GetOfficeNumberById_Call {
	_c.Call.Return(run)
	return _c
}

// GetServicePointByID provides a mock function with given fields: ctx, id
func (_m *MockMainStorage) GetServicePointByID(ctx context.Context, id string) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetServicePointByID")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.ServicePoint, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.ServicePoint); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMainStorage_GetServicePointByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServicePointByID'
type MockMainStorage_GetServicePointByID_Call struct {
	*mock.Call
}

// GetServicePointByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockMainStorage_Expecter) GetServicePointByID(ctx interface{}, id interface{}) *MockMainStorage_GetServicePointByID_Call {
	return &MockMainStorage_GetServicePointByID_Call{Call: _e.mock.On("GetServicePointByID", ctx, id)}
}

func (_c *MockMainStorage_GetServicePointByID_Call) Run(run func(ctx context.Context, id string)) *MockMainStorage_GetServicePointByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMainStorage_GetServicePointByID_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockMainStorage_GetServicePointByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMainStorage_GetServicePointByID_Call) RunAndReturn(run func(context.Context, string) (*models.ServicePoint, error)) *MockMainStorage_GetServicePointByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetShortNameById provides a mock function with given fields: ctx, is
func (_m *MockMainStorage) GetShortNameById(ctx context.Context, is string) (string, error) {
	ret := _m.Called(ctx, is)

	if len(ret) == 0 {
		panic("no return value specified for GetShortNameById")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, is)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, is)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, is)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMainStorage_GetShortNameById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShortNameById'
type MockMainStorage_GetShortNameById_Call struct {
	*mock.Call
}

// GetShortNameById is a helper method to define mock.On call
//   - ctx context.Context
//   - is string
func (_e *MockMainStorage_Expecter) GetShortNameById(ctx interface{}, is interface{}) *MockMainStorage_GetShortNameById_Call {
	return &MockMainStorage_GetShortNameById_Call{Call: _e.mock.On("GetShortNameById", ctx, is)}
}

func (_c *MockMainStorage_GetShortNameById_Call) Run(run func(ctx context.Context, is string)) *MockMainStorage_GetShortNameById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockMainStorage_GetShortNameById_Call) Return(_a0 string, _a1 error) *MockMainStorage_GetShortNameById_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMainStorage_GetShortNameById_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockMainStorage_GetShortNameById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateServicePoint provides a mock function with given fields: ctx, id, sp
func (_m *MockMainStorage) UpdateServicePoint(ctx context.Context, id string, sp models.NewServicePointRequest) (*models.ServicePoint, error) {
	ret := _m.Called(ctx, id, sp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServicePoint")
	}

	var r0 *models.ServicePoint
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, models.NewServicePointRequest) (*models.ServicePoint, error)); ok {
		return rf(ctx, id, sp)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, models.NewServicePointRequest) *models.ServicePoint); ok {
		r0 = rf(ctx, id, sp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ServicePoint)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, models.NewServicePointRequest) error); ok {
		r1 = rf(ctx, id, sp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMainStorage_UpdateServicePoint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateServicePoint'
type MockMainStorage_UpdateServicePoint_Call struct {
	*mock.Call
}

// UpdateServicePoint is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - sp models.NewServicePointRequest
func (_e *MockMainStorage_Expecter) UpdateServicePoint(ctx interface{}, id interface{}, sp interface{}) *MockMainStorage_UpdateServicePoint_Call {
	return &MockMainStorage_UpdateServicePoint_Call{Call: _e.mock.On("UpdateServicePoint", ctx, id, sp)}
}

func (_c *MockMainStorage_UpdateServicePoint_Call) Run(run func(ctx context.Context, id string, sp models.NewServicePointRequest)) *MockMainStorage_UpdateServicePoint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(models.NewServicePointRequest))
	})
	return _c
}

func (_c *MockMainStorage_UpdateServicePoint_Call) Return(_a0 *models.ServicePoint, _a1 error) *MockMainStorage_UpdateServicePoint_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMainStorage_UpdateServicePoint_Call) RunAndReturn(run func(context.Context, string, models.NewServicePointRequest) (*models.ServicePoint, error)) *MockMainStorage_UpdateServicePoint_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMainStorage creates a new instance of MockMainStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMainStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMainStorage {
	mock := &MockMainStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
